---
title: "Atmospheric Conductance Sensitivity Analysis"
author: "Elmera Azadpour, Danielle Sciafani, Desik Somasundaram"
date: '2022-04-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(pse)
```

```{r}
source(here("functions","atmospheric_conductance.R"))
```


```{r}
atmos_conduct(1000, 250)
```

```{r}
# Lets consider 4 of the parameters....
factors = c("h", "k_d", "k_0", "v")

# Decide How many parameter sets to run
nsets=100
# choose distributions for parameters - this would come from
# what you know about the likely range of variation
q = c("qunif","qnorm", "qnorm", "qnorm")
q.arg = list(list(min=950, max=1050),list(mean=0.7,sd=0.007), list(mean=0.1, sd=0.001), list(mean=250,sd=30))

# generate samples from LHS
sens_atmos_cond = LHS(NULL,factors,nsets,q,q.arg)
sens_pars = get.data(sens_atmos_cond)
head(sens_pars)
```

```{r}
# lets now run our model for all of the parameters generated by LHS
# pmap is useful here - it is a map function that uses the actual names of input parameters

atmospheric_conductance = sens_pars %>% pmap(atmos_conduct)
head(atmospheric_conductance)
```
```{r}
# turn results in to a dataframe for easy display/analysis
atmospheric_conductancedf = atmospheric_conductance %>% map_dfr(`[`,c("atmospheric_conductance"))

# to take advantage of LHS/pse functions for 
# plotting interesting information we can send results back - 
# results need to be in a matrix
# each column is a different parameter set - we can use transpose (t)
# and as.matrix to get there

# tell is what links output to original LHS object

sens_atmos_cond = pse::tell(sens_atmos_cond, t(as.matrix(atmospheric_conductancedf)),
                        res.names=c("atmospheric_conductance"))
```
```{r}
# now we use built in LHS functions to analyze parameter sensitivity
pse::plotscatter(sens_atmos_cond, col="blue", cex=5)
```

```{r}
# add uncertainty bounds on our estimates
tmp = atmospheric_conductancedf %>% gather(value="value", key="atmospheric_conductance")
ggplot(tmp, aes(atmospheric_conductance, value, col=atmospheric_conductance))+geom_boxplot()+
  labs(y="Atmospheric Conductance (cm/s)")
```

